---
application:
  name: "web"
  project: "sigfrid.me"
  organization: "QoveryCommunity"
routers:
  custom_domains:
  - branch: master
    domain: sigfrid.me
- name: "main-web"
  routes:
  - application_name: "web"
    paths:
    - "/*"
